# Generated by Django 3.0.5 on 2020-04-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=7)),
                ('celular', models.CharField(max_length=10)),
                ('timeslamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
